### ISSUE TITLE
Create a resource group instead of requiring a config entry for existing resource group

### ISSUE THREAD

**Issue by viveklak** [pulumi/arm2pulumi#24]
Currently arm2pulumi assumes templates are targeting a specific existing resource group. Users may want to create a new resource group instead. The converter should allow an option to do so.

**Comment by MisinformedDNA** [comment]
Yes, and the difficultly I've run into is that get and create return different objects

```csharp
Output<GetResourceGroupResult> rg1= Output.Create(GetResourceGroup.InvokeAsync());
ResourceGroup rg2 = `Output.Create(GetResourceGroup.InvokeAsync())
```

This makes switching from one to the other not completely painless since the property access changes are required.

I have found a couple workarounds

1. Wrap  `new ResourceGroup()` with `Output.Create`. This makes types more interchangeable. This is a good, quick workaround for current ARM2Pulumi conversions.

```csharp 
Output<GetResourceGroupResult> getRG = Output.Create(GetResourceGroup.InvokeAsync());
Output<ResourceGroup> createRG = Output.Create(new ResourceGroup());
```

2. Make two calls for Get

```csharp
var resourceGroupResponse = Output.Create(GetResourceGroup.InvokeAsync(new GetResourceGroupArgs { ResourceGroupName = resourceGroupName }));
ResourceGroup getRG = ResourceGroup.Get("resourceGroup", resourceGroup.Apply(r => r.Id));
ResourceGroup createRG = new ResourceGroup();
```

Assuming I haven't missed anything, this should keep the decision completely interchangeable.

We could even **not** give an option of which, but just include both, with one commented out.

**Comment by mikhailshilkov** [comment]
The standalone arm2pulumi tool has been deprecated in favor of the [Pulumi CLI built-in command](https://www.pulumi.com/docs/cli/commands/pulumi_convert/) `pulumi convert --from arm`. Therefore, I'm closing all issues in this repository as "won't fix". Please file any issue related to `pulumi convert` in https://github.com/pulumi/pulumi/issues/
